name: Run API Tests

on:
  push:
    branches: [ feature/cbatest ]
  pull_request:
    branches: [ feature/cbatest ]
  workflow_dispatch: # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # or whatever version you're using
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Run Tests with Maven
      run: mvn clean test verify
